-- 808Tix MVP: manual verification script
--
-- Prerequisites:
--   1. supabase start && supabase db reset
--   2. Create a test user in Studio Auth and copy the UUID
--   3. Run supabase/dev/auth_simulation.sql once in this SQL session
--   4. Replace v_organizer_id below
--
-- Why dev helpers are required:
--   validate_pass uses auth.uid() and is granted to authenticated only.
--   SQL Editor is not a logged-in app user; dev.set_auth_as() simulates that.

do $$
declare
  v_organizer_id uuid := null; -- REPLACE with auth.users id
  v_event_id uuid;
  v_other_event_id uuid;
  v_pass_id uuid;
  v_token text;
  v_result jsonb;
  v_valid_count bigint;
  v_already_count bigint;
begin
  if v_organizer_id is null then
    raise exception 'Replace v_organizer_id with a real auth.users id before running verification';
  end if;

  if to_regprocedure('dev.set_auth_as(uuid)') is null then
    raise exception 'Run supabase/dev/auth_simulation.sql in this session first';
  end if;

  insert into public.profiles (id, email)
  values (v_organizer_id, 'verify@808tix.test')
  on conflict (id) do nothing;

  -- ---------------------------------------------------------------------------
  -- 1. Create event with slug (superuser / postgres bypasses RLS for setup)
  -- ---------------------------------------------------------------------------
  insert into public.events (
    organizer_id,
    slug,
    name,
    venue_name,
    event_date,
    start_time,
    status
  )
  values (
    v_organizer_id,
    'verify-summer-show',
    'Verification Show',
    'Test Venue',
    current_date + 7,
    '21:00',
    'published'
  )
  returning id into v_event_id;

  raise notice 'event_id: %', v_event_id;

  -- ---------------------------------------------------------------------------
  -- 2. Issue pass (secure_token generated by trigger)
  -- ---------------------------------------------------------------------------
  insert into public.passes (
    event_id,
    guest_name,
    pass_type,
    secure_token
  )
  values (
    v_event_id,
    'Test Guest',
    'GA',
    ''
  )
  returning id, secure_token into v_pass_id, v_token;

  if v_token is null or length(v_token) < 32 then
    raise exception 'secure_token was not generated';
  end if;

  raise notice 'pass_id: %, token: %', v_pass_id, v_token;

  -- ---------------------------------------------------------------------------
  -- 3. Guest view — no auth required; do NOT switch session to anon
  -- ---------------------------------------------------------------------------
  if public.get_pass_by_token(v_token) is null then
    raise exception 'get_pass_by_token returned null for valid token';
  end if;

  if (public.get_pass_by_token(v_token) ->> 'event_slug') <> 'verify-summer-show' then
    raise exception 'get_pass_by_token missing or wrong event_slug';
  end if;

  -- ---------------------------------------------------------------------------
  -- 4. validate_pass — simulate authenticated organizer (JWT + role)
  -- ---------------------------------------------------------------------------
  perform dev.set_auth_as(v_organizer_id);

  if auth.uid() is distinct from v_organizer_id then
    raise exception 'auth simulation failed: auth.uid()=%', auth.uid();
  end if;

  v_result := public.validate_pass(v_token, v_event_id);
  if v_result ->> 'result' <> 'valid' then
    raise exception 'First validate_pass expected valid, got %', v_result;
  end if;

  v_result := public.validate_pass(v_token, v_event_id);
  if v_result ->> 'result' <> 'already_used' then
    raise exception 'Second validate_pass expected already_used, got %', v_result;
  end if;

  reset role;

  select valid_count, already_used_count
  into v_valid_count, v_already_count
  from dev.checkin_counts_for_pass(v_pass_id);

  if v_valid_count <> 1 or v_already_count <> 1 then
    raise exception 'checkins audit mismatch: valid=%, already_used=%', v_valid_count, v_already_count;
  end if;

  if (select status from public.passes where id = v_pass_id) <> 'checked_in' then
    raise exception 'pass status should be checked_in';
  end if;

  -- ---------------------------------------------------------------------------
  -- 5. Wrong event
  -- ---------------------------------------------------------------------------
  insert into public.events (organizer_id, slug, name, status)
  values (v_organizer_id, 'verify-other-night', 'Other Night', 'published')
  returning id into v_other_event_id;

  perform dev.set_auth_as(v_organizer_id);

  v_result := public.validate_pass(v_token, v_other_event_id);
  if v_result ->> 'result' <> 'wrong_event' then
    raise exception 'wrong_event test failed, got %', v_result;
  end if;

  -- ---------------------------------------------------------------------------
  -- 6. Invalid token
  -- ---------------------------------------------------------------------------
  reset role;

  perform dev.set_auth_as(v_organizer_id);

  v_result := public.validate_pass('not-a-real-token', v_event_id);
  if v_result ->> 'result' <> 'invalid' then
    raise exception 'invalid token test failed, got %', v_result;
  end if;

  -- ---------------------------------------------------------------------------
  -- 7. Unauthenticated call must fail (production security)
  -- ---------------------------------------------------------------------------
  reset role;
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claim.role', '', true);

  begin
    v_result := public.validate_pass(v_token, v_event_id);
    raise exception 'Expected unauthenticated validate_pass to fail, got %', v_result;
  exception
    when insufficient_privilege then
      null;
    when sqlstate '42501' then
      null;
  end;

  -- ---------------------------------------------------------------------------
  -- 8. Client cannot change pass status directly (as authenticated owner)
  -- ---------------------------------------------------------------------------
  reset role;

  perform dev.set_auth_as(v_organizer_id);

  begin
    update public.passes
    set status = 'active'
    where id = v_pass_id;
    raise exception 'Expected direct status update to be blocked by trigger';
  exception
    when others then
      if sqlerrm not like '%validate_pass%' then
        raise;
      end if;
  end;

  reset role;
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claim.role', '', true);

  raise notice 'All verification checks passed.';
end;
$$;

-- =============================================================================
-- Optional: slug uniqueness (run separately)
-- =============================================================================
-- insert into public.events (organizer_id, slug, name)
-- values ('<organizer-uuid>', 'verify-summer-show', 'Duplicate')
-- should fail with unique_violation on events_slug_unique
