-- 808Tix MVP: manual verification script
--
-- Run after migrations (and optional seed) against local Supabase.
--
-- Prerequisites:
--   1. supabase start
--   2. supabase db reset   (applies migrations)
--   3. Create a test user in Studio Auth (or via signUp) and note the user UUID
--   4. Replace :organizer_id below with that UUID
--
-- Run in SQL Editor as service role, OR set request.jwt.claim.sub for RPC tests:
--   select set_config('request.jwt.claim.sub', '<organizer-uuid>', true);
--   select set_config('request.jwt.claim.role', 'authenticated', true);

-- =============================================================================
-- SETUP (edit organizer id)
-- =============================================================================
-- \set organizer_id '00000000-0000-0000-0000-000000000000'

do $$
declare
  v_organizer_id uuid := '00000000-0000-0000-0000-000000000000'; -- REPLACE
  v_event_id uuid;
  v_pass_id uuid;
  v_token text;
  v_result jsonb;
  v_valid_count int;
  v_already_count int;
begin
  if v_organizer_id = '00000000-0000-0000-0000-000000000000'::uuid then
    raise exception 'Replace v_organizer_id with a real auth.users id before running verification';
  end if;

  -- Ensure profile exists (trigger should have created it on signup)
  insert into public.profiles (id, email)
  values (v_organizer_id, 'verify@808tix.test')
  on conflict (id) do nothing;

  -- ---------------------------------------------------------------------------
  -- 1. Create event with slug
  -- ---------------------------------------------------------------------------
  insert into public.events (
    organizer_id,
    slug,
    name,
    venue_name,
    event_date,
    start_time,
    status
  )
  values (
    v_organizer_id,
    'verify-summer-show',
    'Verification Show',
    'Test Venue',
    current_date + 7,
    '21:00',
    'published'
  )
  returning id into v_event_id;

  raise notice 'event_id: %', v_event_id;

  -- ---------------------------------------------------------------------------
  -- 2. Issue pass (secure_token generated by trigger)
  -- ---------------------------------------------------------------------------
  insert into public.passes (
    event_id,
    guest_name,
    pass_type,
    secure_token
  )
  values (
    v_event_id,
    'Test Guest',
    'GA',
    ''
  )
  returning id, secure_token into v_pass_id, v_token;

  if v_token is null or length(v_token) < 32 then
    raise exception 'secure_token was not generated';
  end if;

  raise notice 'pass_id: %, token: %', v_pass_id, v_token;

  -- ---------------------------------------------------------------------------
  -- 3. Guest view (anon) — run separately as anon in Studio if preferred
  -- ---------------------------------------------------------------------------
  perform set_config('role', 'anon', true);
  -- get_pass_by_token works via SECURITY DEFINER; test as superuser here:
  if public.get_pass_by_token(v_token) is null then
    raise exception 'get_pass_by_token returned null for valid token';
  end if;

  if (public.get_pass_by_token(v_token) ->> 'event_slug') <> 'verify-summer-show' then
    raise exception 'get_pass_by_token missing or wrong event_slug';
  end if;

  -- ---------------------------------------------------------------------------
  -- 4. validate_pass — simulate authenticated organizer
  -- ---------------------------------------------------------------------------
  perform set_config('request.jwt.claim.sub', v_organizer_id::text, true);
  perform set_config('request.jwt.claim.role', 'authenticated', true);

  v_result := public.validate_pass(v_token, v_event_id);
  if v_result ->> 'result' <> 'valid' then
    raise exception 'First validate_pass expected valid, got %', v_result;
  end if;

  v_result := public.validate_pass(v_token, v_event_id);
  if v_result ->> 'result' <> 'already_used' then
    raise exception 'Second validate_pass expected already_used, got %', v_result;
  end if;

  select count(*) filter (where result = 'valid'),
         count(*) filter (where result = 'already_used')
  into v_valid_count, v_already_count
  from public.checkins
  where pass_id = v_pass_id;

  if v_valid_count <> 1 or v_already_count <> 1 then
    raise exception 'checkins audit mismatch: valid=%, already_used=%', v_valid_count, v_already_count;
  end if;

  if (select status from public.passes where id = v_pass_id) <> 'checked_in' then
    raise exception 'pass status should be checked_in';
  end if;

  -- ---------------------------------------------------------------------------
  -- 5. Wrong event
  -- ---------------------------------------------------------------------------
  insert into public.events (organizer_id, slug, name, status)
  values (v_organizer_id, 'verify-other-night', 'Other Night', 'published');

  v_result := public.validate_pass(
    v_token,
    (select id from public.events where slug = 'verify-other-night')
  );
  if v_result ->> 'result' <> 'wrong_event' then
    raise exception 'wrong_event test failed, got %', v_result;
  end if;

  -- ---------------------------------------------------------------------------
  -- 6. Invalid token
  -- ---------------------------------------------------------------------------
  v_result := public.validate_pass('not-a-real-token', v_event_id);
  if v_result ->> 'result' <> 'invalid' then
    raise exception 'invalid token test failed, got %', v_result;
  end if;

  -- ---------------------------------------------------------------------------
  -- 7. Client cannot change pass status directly
  -- ---------------------------------------------------------------------------
  begin
    update public.passes
    set status = 'active'
    where id = v_pass_id;
    raise exception 'Expected direct status update to be blocked by trigger';
  exception
    when others then
      if sqlerrm not like '%validate_pass%' then
        raise;
      end if;
  end;

  raise notice 'All verification checks passed.';
end;
$$;

-- =============================================================================
-- Optional: slug uniqueness
-- =============================================================================
-- insert into public.events (organizer_id, slug, name)
-- values ('<organizer-uuid>', 'verify-summer-show', 'Duplicate')
-- should fail with unique_violation on events_slug_unique
