import { StyleSheet } from 'react-native';

import { organizer, palette, surface, text } from '@/theme/colors';

export const adminStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: surface.background },
  content: { padding: 20, paddingBottom: 60, maxWidth: 1100, width: '100%', alignSelf: 'center' },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, gap: 12 },
  h1: { color: palette.white, fontSize: 28, fontWeight: '800', marginBottom: 4 },
  h2: { color: palette.white, fontSize: 20, fontWeight: '700', marginTop: 28, marginBottom: 12 },
  h3: { color: text.secondary, fontSize: 16, fontWeight: '700', marginTop: 12, marginBottom: 8 },
  muted: { color: text.secondary, fontSize: 13, lineHeight: 18 },
  body: { color: text.primary, fontSize: 14, lineHeight: 20, marginTop: 4 },
  error: { color: '#FF6B6B', marginTop: 12, marginBottom: 8 },
  cardGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  card: {
    backgroundColor: surface.card,
    borderRadius: 12,
    padding: 14,
    minWidth: 160,
    flexGrow: 1,
    borderWidth: 1,
    borderColor: surface.divider,
  },
  cardLabel: { color: text.secondary, fontSize: 12, marginBottom: 6 },
  cardValue: { color: organizer.accent, fontSize: 18, fontWeight: '700' },
  rowCard: {
    backgroundColor: surface.card,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: surface.divider,
    gap: 4,
  },
  rowTitle: { color: palette.white, fontSize: 16, fontWeight: '700' },
  rowTitleLink: { color: organizer.accent, fontSize: 16, fontWeight: '700', textDecorationLine: 'underline' },
  btnRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  linkBtn: {
    borderWidth: 1,
    borderColor: organizer.accent,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  linkBtnText: { color: organizer.accent, fontSize: 12, fontWeight: '600' },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  input: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: surface.divider,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: palette.white,
    backgroundColor: surface.input,
  },
  feeField: { marginBottom: 8 },
  primaryBtn: {
    marginTop: 12,
    backgroundColor: organizer.accent,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  primaryBtnText: { color: organizer.textOn, fontWeight: '800' },
  disabled: { opacity: 0.6 },
  toggleRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8, marginBottom: 8 },
  toggleActive: {
    backgroundColor: organizer.accent,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  toggleIdle: {
    borderWidth: 1,
    borderColor: organizer.accent,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  toggleActiveText: { color: organizer.textOn, fontSize: 12, fontWeight: '700' },
  toggleIdleText: { color: organizer.accent, fontSize: 12, fontWeight: '600' },
});
