import { StyleSheet } from 'react-native';

/** Isolated tokens for the admin dashboard design prototype. */
export const proto = {
  bg: '#0A0A12',
  bgElevated: '#12121C',
  card: '#161622',
  cardBorder: 'rgba(255,255,255,0.06)',
  magenta: '#FF2D78',
  magentaSoft: 'rgba(255,45,120,0.16)',
  purple: '#A25BFF',
  violet: '#7B8CFF',
  rose: '#FF5C8A',
  green: '#39FF14',
  greenSoft: 'rgba(57,255,20,0.14)',
  amber: '#FFB020',
  amberSoft: 'rgba(255,176,32,0.14)',
  blueSoft: 'rgba(123,140,255,0.16)',
  text: '#FFFFFF',
  textMuted: '#9AA0AE',
  textDim: '#6F7686',
  divider: 'rgba(255,255,255,0.07)',
  input: '#1A1A28',
} as const;

export const prototypeStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: proto.bg },
  scroll: { paddingBottom: 64 },
  page: {
    width: '100%',
    maxWidth: 1240,
    alignSelf: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 22,
    flexWrap: 'wrap',
  },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  brandMark: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: proto.magenta,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandMarkText: { color: '#000', fontWeight: '900', fontSize: 13 },
  brandName: { color: proto.text, fontSize: 18, fontWeight: '800', letterSpacing: 0.2 },
  navRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  navChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'transparent',
  },
  navChipActive: { backgroundColor: proto.magentaSoft },
  navChipText: { color: proto.textMuted, fontSize: 13, fontWeight: '600' },
  navChipTextActive: { color: proto.magenta },
  topTools: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  searchBox: {
    minWidth: 160,
    flexGrow: 1,
    maxWidth: 240,
    backgroundColor: proto.input,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  searchText: { color: proto.textDim, fontSize: 13 },
  datePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    backgroundColor: proto.card,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  datePillText: { color: proto.textMuted, fontSize: 12, fontWeight: '600' },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#2A2A3C',
    borderWidth: 1,
    borderColor: proto.magenta,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: proto.text, fontSize: 12, fontWeight: '800' },
  titleBlock: { marginBottom: 18 },
  h1: { color: proto.text, fontSize: 30, fontWeight: '800', letterSpacing: -0.4 },
  subtitle: { color: proto.textMuted, fontSize: 14, marginTop: 6, lineHeight: 20 },
  kpiRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 16 },
  kpiCard: {
    flexGrow: 1,
    flexBasis: 180,
    minWidth: 160,
    backgroundColor: proto.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    padding: 14,
    gap: 8,
  },
  kpiIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  kpiIconText: { fontSize: 13, fontWeight: '800' },
  kpiLabel: { color: proto.textMuted, fontSize: 12, fontWeight: '600' },
  kpiValue: { color: proto.text, fontSize: 22, fontWeight: '800', letterSpacing: -0.3 },
  kpiTrend: { color: proto.green, fontSize: 11, fontWeight: '600' },
  midRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 16 },
  chartCard: {
    flexGrow: 2,
    flexBasis: 420,
    minWidth: 280,
    backgroundColor: proto.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    padding: 16,
  },
  summaryCard: {
    flexGrow: 1,
    flexBasis: 260,
    minWidth: 240,
    backgroundColor: proto.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    padding: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 14,
    flexWrap: 'wrap',
  },
  sectionTitle: { color: proto.text, fontSize: 17, fontWeight: '700' },
  rangeRow: { flexDirection: 'row', gap: 6 },
  rangeChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: proto.cardBorder,
  },
  rangeChipActive: { borderColor: proto.magenta, backgroundColor: proto.magentaSoft },
  rangeChipText: { color: proto.textMuted, fontSize: 12, fontWeight: '600' },
  rangeChipTextActive: { color: proto.magenta },
  chartWrap: { height: 220, marginTop: 4 },
  axisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  axisLabel: { color: proto.textDim, fontSize: 11 },
  splitRow: { flexDirection: 'row', alignItems: 'center', gap: 14, marginTop: 8 },
  splitLegend: { flex: 1, gap: 10 },
  legendItem: { gap: 2 },
  legendTop: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendLabel: { color: proto.textMuted, fontSize: 12 },
  legendValue: { color: proto.text, fontSize: 14, fontWeight: '700', marginLeft: 16 },
  eventsCard: {
    backgroundColor: proto.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    padding: 16,
    overflow: 'hidden',
  },
  eventsTools: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  filterPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: proto.input,
  },
  filterText: { color: proto.textMuted, fontSize: 12, fontWeight: '600' },
  primaryBtn: {
    borderRadius: 999,
    backgroundColor: proto.magenta,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  primaryBtnText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  tableScroll: { marginTop: 8 },
  tableMin: { minWidth: 980 },
  tableHead: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: proto.divider,
    paddingBottom: 10,
    marginBottom: 4,
  },
  th: { color: proto.textDim, fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.4 },
  tr: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: proto.divider,
  },
  td: { color: proto.textMuted, fontSize: 13 },
  tdStrong: { color: proto.text, fontSize: 13, fontWeight: '700' },
  tdNet: { color: proto.green, fontSize: 13, fontWeight: '800' },
  eventCell: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  thumb: { width: 40, height: 40, borderRadius: 10 },
  eventMeta: { flex: 1, gap: 4 },
  eventName: { color: proto.text, fontSize: 13, fontWeight: '700' },
  badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  badge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  badgeText: { fontSize: 10, fontWeight: '800' },
  footerRow: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  footerText: { color: proto.textDim, fontSize: 12 },
  pageRow: { flexDirection: 'row', gap: 6 },
  pageBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageBtnActive: { borderColor: proto.magenta },
  pageBtnText: { color: proto.textMuted, fontSize: 12, fontWeight: '700' },
  pageBtnTextActive: { color: proto.magenta },
  mobileCards: { gap: 10, marginTop: 8 },
  mobileEventCard: {
    borderWidth: 1,
    borderColor: proto.cardBorder,
    borderRadius: 14,
    padding: 12,
    gap: 8,
    backgroundColor: proto.bgElevated,
  },
  breadcrumbRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
    marginBottom: 14,
  },
  breadcrumbLink: { color: proto.magenta, fontSize: 13, fontWeight: '700' },
  breadcrumbSep: { color: proto.textDim, fontSize: 13 },
  breadcrumbCurrent: { color: proto.textMuted, fontSize: 13, fontWeight: '600', flexShrink: 1 },
  heroCard: {
    backgroundColor: proto.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    padding: 16,
    gap: 12,
    marginBottom: 16,
  },
  heroTop: { flexDirection: 'row', gap: 14, alignItems: 'flex-start' },
  heroThumb: { width: 72, height: 72, borderRadius: 16 },
  heroBody: { flex: 1, gap: 8 },
  heroTitle: { color: proto.text, fontSize: 24, fontWeight: '800', letterSpacing: -0.3 },
  fieldGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  fieldBlock: { minWidth: 140, flexGrow: 1, gap: 3 },
  fieldLabel: {
    color: proto.textDim,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  fieldValue: { color: proto.text, fontSize: 14, fontWeight: '600', lineHeight: 20 },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  ghostBtn: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: proto.input,
  },
  ghostBtnText: { color: proto.textMuted, fontSize: 12, fontWeight: '700' },
  sectionCard: {
    backgroundColor: proto.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    padding: 16,
    marginBottom: 14,
    gap: 10,
  },
  orderCard: {
    borderWidth: 1,
    borderColor: proto.cardBorder,
    borderRadius: 14,
    padding: 12,
    gap: 8,
    backgroundColor: proto.bgElevated,
  },
  metricMiniGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  metricMini: {
    minWidth: 96,
    flexGrow: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: proto.cardBorder,
    backgroundColor: 'rgba(255,255,255,0.03)',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  metricMiniLabel: { color: proto.textDim, fontSize: 11, marginBottom: 2 },
  metricMiniValue: { color: proto.text, fontSize: 14, fontWeight: '700' },
  protoNote: {
    marginTop: 18,
    color: proto.textDim,
    fontSize: 11,
    textAlign: 'center',
  },
});