import { StyleSheet } from 'react-native';

import { dash } from '@/components/dashboard/dashboard-tokens';

export const dashboardStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: dash.bg },
  scroll: { paddingBottom: 64 },
  page: {
    width: '100%',
    maxWidth: 1240,
    alignSelf: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    gap: 12,
  },
  titleBlock: { marginBottom: 18 },
  h1: { color: dash.text, fontSize: 30, fontWeight: '800', letterSpacing: -0.4 },
  subtitle: { color: dash.textMuted, fontSize: 14, marginTop: 6, lineHeight: 20 },
  h2: { color: dash.text, fontSize: 17, fontWeight: '700' },
  muted: { color: dash.textMuted, fontSize: 13, lineHeight: 18 },
  error: { color: dash.error, marginTop: 8, marginBottom: 8, fontSize: 13 },
  kpiRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 16 },
  kpiCard: {
    flexGrow: 1,
    flexBasis: 160,
    minWidth: 148,
    backgroundColor: dash.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: dash.cardBorder,
    padding: 14,
    gap: 6,
  },
  kpiLabel: { color: dash.textMuted, fontSize: 12, fontWeight: '600' },
  kpiValue: { color: dash.text, fontSize: 22, fontWeight: '800', letterSpacing: -0.3 },
  kpiHint: { color: dash.textDim, fontSize: 11, lineHeight: 15 },
  midRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 16 },
  chartCard: {
    flexGrow: 2,
    flexBasis: 420,
    minWidth: 280,
    backgroundColor: dash.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: dash.cardBorder,
    padding: 16,
  },
  summaryCard: {
    flexGrow: 1,
    flexBasis: 260,
    minWidth: 240,
    backgroundColor: dash.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: dash.cardBorder,
    padding: 16,
  },
  sectionCard: {
    backgroundColor: dash.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: dash.cardBorder,
    padding: 16,
    marginBottom: 14,
    gap: 10,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 14,
    flexWrap: 'wrap',
  },
  sectionTitle: { color: dash.text, fontSize: 17, fontWeight: '700' },
  sectionTools: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  chartWrap: { height: 200, marginTop: 4 },
  chartEmpty: {
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: dash.cardBorder,
    backgroundColor: dash.bgElevated,
    padding: 16,
    gap: 8,
  },
  axisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  axisLabel: { color: dash.textDim, fontSize: 11 },
  splitRow: { flexDirection: 'row', alignItems: 'center', gap: 14, marginTop: 8 },
  splitLegend: { flex: 1, gap: 10 },
  legendItem: { gap: 2 },
  legendTop: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendLabel: { color: dash.textMuted, fontSize: 12 },
  legendValue: { color: dash.text, fontSize: 14, fontWeight: '700', marginLeft: 16 },
  badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  badge: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
  badgeText: { fontSize: 10, fontWeight: '800' },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  metricChip: {
    minWidth: 96,
    flexGrow: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: dash.cardBorder,
    backgroundColor: 'rgba(255,255,255,0.03)',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  metricLabel: { color: dash.textDim, fontSize: 11, marginBottom: 2 },
  metricValue: { color: dash.text, fontSize: 14, fontWeight: '700' },
  metricValueAccent: { color: dash.green, fontSize: 14, fontWeight: '800' },
  fieldBlock: { minWidth: 140, flexGrow: 1, gap: 3 },
  fieldLabel: {
    color: dash.textDim,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  fieldValue: { color: dash.text, fontSize: 14, fontWeight: '600', lineHeight: 20 },
  ghostBtn: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: dash.cardBorder,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: dash.input,
  },
  ghostBtnText: { color: dash.textMuted, fontSize: 12, fontWeight: '700' },
  primaryBtn: {
    borderRadius: 999,
    backgroundColor: dash.magenta,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: 'center',
  },
  primaryBtnText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  disabled: { opacity: 0.6 },
  searchBox: {
    minWidth: 140,
    flexGrow: 1,
    maxWidth: 220,
    backgroundColor: dash.input,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: dash.cardBorder,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  searchInput: { color: dash.text, fontSize: 13, padding: 0 },
  mobileCards: { gap: 10 },
  mobileEventCard: {
    borderWidth: 1,
    borderColor: dash.cardBorder,
    borderRadius: 14,
    padding: 12,
    gap: 8,
    backgroundColor: dash.bgElevated,
  },
  eventNameLink: { color: dash.magenta, fontSize: 16, fontWeight: '800' },
  eventMeta: { color: dash.textMuted, fontSize: 13, lineHeight: 18 },
  tableScroll: { marginTop: 4 },
  tableMin: { minWidth: 980 },
  tableHead: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: dash.divider,
    paddingBottom: 10,
    marginBottom: 4,
  },
  th: {
    color: dash.textDim,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  tr: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: dash.divider,
  },
  td: { color: dash.textMuted, fontSize: 13 },
  tdStrong: { color: dash.text, fontSize: 13, fontWeight: '700' },
  input: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: dash.cardBorder,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    color: dash.text,
    backgroundColor: dash.input,
    fontSize: 14,
  },
  feeField: { marginBottom: 10 },
  feeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 8 },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    gap: 8,
  },
  emptyTitle: { color: dash.textMuted, fontSize: 14, fontWeight: '700' },
  emptyBody: { color: dash.textDim, fontSize: 12, textAlign: 'center', lineHeight: 18 },
});
