import type { DashboardEventRow } from '@/components/dashboard/event-list';

/** Static mock data for /design/admin-dashboard-review only — not used by production /admin. */

export const REVIEW_SUMMARY = {
  ticket_subtotal_cents: 1842500,
  paid_tickets_issued_count: 1247,
  checked_in_count: 892,
  pending_payout_count: 3,
  platform_fee_cents: 245600,
  processing_fee_cents: 98200,
  organizer_net_cents: 1596900,
} as const;

export const REVIEW_CHART_SERIES = [
  0.18,
  0.32,
  0.28,
  0.41,
  0.36,
  0.52,
  0.48,
  0.61,
  0.55,
  0.72,
  0.68,
  0.84,
  0.78,
  0.92,
] as const;

export const REVIEW_CHART_LABELS = [
  'Aug 1',
  'Aug 3',
  'Aug 5',
  'Aug 7',
  'Aug 9',
  'Aug 11',
  'Aug 13',
  'Aug 15',
  'Aug 17',
  'Aug 19',
  'Aug 21',
  'Aug 23',
  'Aug 25',
  'Aug 27',
] as const;

export const REVIEW_CHART_Y_AXIS: [string, string, string] = ['$0', '$10K', '$20K'];

export const REVIEW_MONETIZATION = {
  platform_fee_bps: 250,
  platform_fee_fixed_cents: 99,
  processing_fee_bps: 290,
  processing_fee_fixed_cents: 30,
  precedence: ['event', 'organizer', 'global'] as const,
};

export const REVIEW_EVENTS: DashboardEventRow[] = [
  {
    eventId: 'review-event-1',
    eventName: 'Neon Nights at The Loft',
    whenLabel: 'Sat, Aug 30 · 9:00 PM',
    venueName: 'The Loft, Portland',
    organizerEmail: 'mia@nightshift.events',
    statusLabel: 'Published',
    statusTone: 'positive',
    buyabilityLabel: 'Selling',
    buyabilityTone: 'positive',
    feeSourceLabel: 'Global',
    payoutLabel: 'Pending',
    paidOrderCount: 186,
    paidTicketCount: 412,
    checkedInCount: 0,
    ticketSubtotalLabel: '$8,240',
    platformFeeLabel: '$1,098',
    processingFeeLabel: '$438',
    organizerNetLabel: '$7,162',
  },
  {
    eventId: 'review-event-2',
    eventName: 'Brewery Sessions: IPA Release',
    whenLabel: 'Fri, Sep 5 · 6:00 PM',
    venueName: 'Cascade Brewing Hall',
    organizerEmail: 'derek@cascadebrew.com',
    statusLabel: 'Published',
    statusTone: 'positive',
    buyabilityLabel: 'Selling',
    buyabilityTone: 'positive',
    feeSourceLabel: 'Organizer',
    payoutLabel: 'Paid',
    paidOrderCount: 94,
    paidTicketCount: 210,
    checkedInCount: 0,
    ticketSubtotalLabel: '$4,200',
    platformFeeLabel: '$560',
    processingFeeLabel: '$224',
    organizerNetLabel: '$3,640',
  },
  {
    eventId: 'review-event-3',
    eventName: 'Warehouse Rave — Labor Day',
    whenLabel: 'Sun, Sep 7 · 10:00 PM',
    venueName: 'Dock 9 Warehouse',
    organizerEmail: 'crew@808underground.com',
    statusLabel: 'Draft',
    statusTone: 'draft',
    buyabilityLabel: 'Draft',
    buyabilityTone: 'draft',
    feeSourceLabel: 'Event',
    payoutLabel: 'None',
    paidOrderCount: 0,
    paidTicketCount: 0,
    checkedInCount: 0,
    ticketSubtotalLabel: '$0',
    platformFeeLabel: '$0',
    processingFeeLabel: '$0',
    organizerNetLabel: '$0',
  },
  {
    eventId: 'review-event-4',
    eventName: 'Sunset Sessions — Waikiki',
    whenLabel: 'Sat, Aug 16 · 5:30 PM',
    venueName: 'Waikiki Beach Park',
    organizerEmail: 'aloha@islandvibes.co',
    statusLabel: 'Published',
    statusTone: 'positive',
    buyabilityLabel: 'Sold out',
    buyabilityTone: 'warn',
    feeSourceLabel: 'Global',
    payoutLabel: 'Paid',
    paidOrderCount: 312,
    paidTicketCount: 535,
    checkedInCount: 512,
    ticketSubtotalLabel: '$5,350',
    platformFeeLabel: '$712',
    processingFeeLabel: '$285',
    organizerNetLabel: '$4,638',
  },
  {
    eventId: 'review-event-5',
    eventName: 'Comedy Night at Hana Hou',
    whenLabel: 'Thu, Aug 28 · 8:00 PM',
    venueName: 'Hana Hou Cafe',
    organizerEmail: 'bookings@hanahou.com',
    statusLabel: 'Published',
    statusTone: 'positive',
    buyabilityLabel: 'Sales off',
    buyabilityTone: 'warn',
    feeSourceLabel: 'Global',
    payoutLabel: 'Pending',
    paidOrderCount: 67,
    paidTicketCount: 100,
    checkedInCount: 0,
    ticketSubtotalLabel: '$2,000',
    platformFeeLabel: '$266',
    processingFeeLabel: '$106',
    organizerNetLabel: '$1,734',
  },
];
